<img src="https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/numpy_logo.png?raw=1" alt="logo" width="400"/>

## Introduction to numpy

NumPy stands for 'Numerical Python'. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrixes, along with many high-level mathematical functions that operate on them. It contains among other things:

→ a powerful N-dimensional array object.

→ sophisticated (broadcasting) functions.

→ tools for integrating C/C++ and Fortran code.

→ useful linear algebra, Fourier transform, and random number capabilities.

## Installing NumPy
When you want to work with numpy locally, you should run the following commands:

You can install NumPy with:\
`pip install numpy`\
or\
`conda install numpy`

In our case, 4Geeks have prepared all the environment in order that you can work comfortably.

## Why should we use NumPy?

Numpy is a library that performs numerical calculations in python. We will use it mainly because it allows us to create, modify matrixes, and do operations on them with ease.

NumPy is like Pandas, Matplotlib or Scikit-Learn. It is one of the packages that you cannot miss when you are studying Machine Learning. Mainly because this library provides a matrix data structure that has some benefits over regular Python lists. Some of these benefits are: being more compact, quicker access to reading and writing articles, more convenient and efficient.

For example, we will see later in the bootcamp that working with images is dealing with three-dimensional matrixes as large as 3840 x 2160, which means we will have 3×3840×2160 = 24883200 entries!!! 😱😱😱.

Working with matrixes of that magnitude is practically impossible to carry out with lists and dictionaries if one wants to have an efficient and fast programming.

#### Exercise: Import the numpy package under the name `np` (★☆☆)

`numpy` is commonly imported as `np` so we highly recommend to put this alias.

In [1]:
import numpy as np

## What is an array and why it is important for Machine Learning?

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one index or key.


![alt text](assets/1D.png "1D")

An array is known as the central data structure of the Numpy library; it can also be of several dimensions. For example, neural networks sometimes deal with 4D arrays.

Later on, we are also going to use another kind of arrays called: Tensors.

![alt text](./assets/3D.png "3D")

#### Exercise: Print the version and configuration of numpy (★☆☆)

You can print the version of any package of Python using `name_of_package.__version__`

In [ ]:
import numpy as np
print(np.__version__)

1.21.3


#### Exercise: Create a null vector of size 10 (★☆☆)

A `null vector` is an array of zeros (`0`), also called `initialization vector`.

>Check de function `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Exercise: Create a vector of ones with size 10 (★☆☆)

>Check de function `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise: Create an 1D array with a specific start value, end value, and number of values (★☆☆)

>Check the function `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [4]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

#### Run: Create a vector (1D array) with random integers from 10 to 49 and dimension 1x35 (★☆☆)

When `dimension` is expressed `1x35` it means: One dimension array with 35 items (length=35).

>Check the function `np.random` which allows you to create random arrays (https://numpy.org/doc/1.16/reference/routines.random.html)

In [12]:
import numpy as np

## 10 random numbers between (0, 1)
print(np.random.random(10)) 

[0.90666705 0.70121841 0.9617762  0.43889271 0.5323519  0.22807794
 0.62892901 0.34939372 0.25170211 0.10926433]


In [13]:
## Two ways to create numbers with normal distribution
print(np.random.rand(10)) # 10 random values with distribution N(0,1)
print(np.random.normal(loc = 0, scale = 1, size = 10)) # 10 random values with distribution N(0,1)

[0.66916193 0.91645771 0.90681464 0.13585408 0.51812297 0.78101946
 0.26139777 0.98544708 0.46759922 0.13630126]
[-0.40083568  1.91067682 -0.67016031 -1.92192514  0.95808487  0.13669545
 -1.63584847  0.36359165  0.63828228  1.09244371]


In [7]:
## Did you notice the difference between both functions? 
print(np.random.normal(loc = -5, scale = 33, size = 10)) # 10 random values with distribution N(-5,33)

[ 38.99557603  40.36385416 -13.96816617 -17.65426979   2.34587517
  11.93450689   1.68958439  48.58208172  37.30408387  35.37720604]


In [8]:
## 10 random values with uniform distribution. That means, all values have the same probability
print(np.random.uniform(-30,100,10)) # All values are between -30 and 100.

[ 74.52624739   2.72296565  45.75252264  44.92848297  -8.81274528
 -19.03464485  57.84577544  32.56189166  42.17003072  95.73155888]


In [9]:
# 10 integers values between 0 and 100.
print(np.random.randint(0, 100, 10))

[78  8 65 17 67 85 91 20 44 46]


In [10]:
# 10 random values with Chi distribution with 5 degrees of freedom
print(np.random.chisquare(5,10))

[12.11213674  4.33656542  0.43534211  6.89514359  9.71031171  4.6660105
  2.06807835  8.02856223  1.85624211 13.54187938]


The above examples are the most common distribution and random values you will learn throughout the bootcamp. Now, let's deal with those arrays.

#### Exercise: Reverse one of the last vector we created before (first element becomes last) (★☆☆)
Try with `[::-1]`

In [15]:
vector = np.random.randint(0, 50, 5) # 5 integers values between 0 and 50
print(vector)
print(vector[::-1])

[23  2  1 43  5]
[ 5 43  1  2 23]


#### Exercise: Create a 5x5 identity matrix (★☆☆)

>Check the function `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [19]:
#An identity matrix is a given square matrix of any order which contains on its main diagonal elements with value of one, while the rest of the matrix elements are equal to zero.

identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Exercise: Find indexes of non-zero elements from [1,2,0,0,4,0] (★☆☆)

>Check the function `where`(https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [20]:
v = [1,2,0,0,4,0]
#nonzero is the function that is called when x and y are omitted
print(np.where(v))

(array([0, 1, 4]),)


#### Exercise: Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

>Check the function `min` (https://numpy.org/devdocs/reference/generated/numpy.where.html) and `max` (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [35]:
m = np.random.randint(0, 100, (10,10))
print(m.max())
print(m.min())



99
2


#### Exercise: Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
random_v = np.random.randint(0, 100, 30)
print(random_v)
print(np.mean(random_v))

[69 99 79 45 22 49 96 29 93 30 63 20 69 29 62 82  5 69 70 26 33 69 23 30
  3 24 14 97 28 40]
48.9


#### Exercise: Define a function with your date of birth (yyyy/mm/dd) as imput, that returns a random array with the following dimensions: (★★☆)

$$yyyy-1900 \times |mm - dd|$$

In [56]:
import datetime

def birth_matrix(x):
  year = int(x.strftime("%Y"))
  month = int(x.strftime("%m"))
  day = int(x.strftime("%d"))
  dim1 = year - 1900
  dim2 = np.abs(month-day)
  matrix = np.random.rand(dim1,dim2)
  return dim1,dim2,matrix


print(birth_matrix(datetime.datetime(1998, 12, 13)))




(98, 1, array([[0.41594918],
       [0.81757403],
       [0.20169665],
       [0.36760688],
       [0.72451902],
       [0.71549948],
       [0.35949563],
       [0.86145386],
       [0.32045627],
       [0.59178504],
       [0.60296646],
       [0.12566557],
       [0.55055126],
       [0.58856042],
       [0.29916503],
       [0.83180172],
       [0.48396355],
       [0.15164763],
       [0.79411552],
       [0.62711273],
       [0.51866337],
       [0.84495176],
       [0.91979374],
       [0.20323151],
       [0.96702115],
       [0.06128485],
       [0.24929446],
       [0.486322  ],
       [0.3575688 ],
       [0.69057456],
       [0.51506658],
       [0.91018835],
       [0.49474677],
       [0.89371406],
       [0.3470399 ],
       [0.6545827 ],
       [0.59203458],
       [0.84965489],
       [0.88444362],
       [0.42155761],
       [0.7346636 ],
       [0.03708347],
       [0.55833519],
       [0.26435889],
       [0.8281408 ],
       [0.77056446],
       [0.749749  ],
     

## What is the difference between Python List and a Numpy Array?

- Python list can contain elements with different data types, while Numpy Array‘s elements are always homogeneous (same data types).

- Numpy arrays are faster and more compact than Python lists.

## Why Numpy Arrays are faster than Lists?

- Numpy Arrays use fixed memory to store data and less memory than Python lists.

- Contiguous memory allocation in Numpy Arrays.

#### Exercise: Convert the list `my_list = [1, 2, 3]` to numpy array (★☆☆)

In [66]:
my_list = [1,2,3]

arr = np.asarray(my_list)


print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3]


#### Exercise: Convert the tuple `my_list = (1, 2, 3)` to numpy array (★☆☆)

In [65]:
my_tuple = (1,2,3)

a = np.asarray(my_tuple)


print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


#### Exercise: Convert the list of tuples `my_list = [(1,2,3), (4,5)]` to numpy array (★☆☆)

In [74]:
list_of_tuples = [(1,2,3), (4,5)]
np_arr = np.array(list_of_tuples, dtype=object)


print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


#### Exercise: Resize a random array of dimensions 5x12 into 12x5 (★☆☆)

>Check `reshape` from `numpy` (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [80]:
random_array = np.random.rand(5,12)
print(random_array)
reshape_array = np.reshape(random_array,(12,5))
print(reshape_array)

[[0.31939651 0.01359961 0.62101228 0.50531806 0.05160676 0.29252249
  0.4830068  0.47943383 0.09894356 0.90653853 0.37322175 0.86728739]
 [0.39344269 0.11764884 0.11001125 0.00187505 0.73029581 0.25411566
  0.05174184 0.70644298 0.60264884 0.69751349 0.98006429 0.23772388]
 [0.79206408 0.49351712 0.87759074 0.88747274 0.4825026  0.13291337
  0.32215634 0.46529666 0.19903885 0.13071506 0.24012086 0.48174999]
 [0.74365162 0.68483726 0.46338753 0.42117317 0.54774768 0.71809626
  0.91151225 0.35139443 0.04076093 0.86439275 0.70674754 0.08109307]
 [0.47454314 0.57410023 0.21504592 0.64818057 0.6423083  0.60266615
  0.46605863 0.01319036 0.05514588 0.49848604 0.5534186  0.96115684]]
[[0.31939651 0.01359961 0.62101228 0.50531806 0.05160676]
 [0.29252249 0.4830068  0.47943383 0.09894356 0.90653853]
 [0.37322175 0.86728739 0.39344269 0.11764884 0.11001125]
 [0.00187505 0.73029581 0.25411566 0.05174184 0.70644298]
 [0.60264884 0.69751349 0.98006429 0.23772388 0.79206408]
 [0.49351712 0.87759074 

#### Exercise: Create a function that normalize a 5x5 random matrix (★☆☆)

>Remember from probability (https://en.wikipedia.org/wiki/Normalization_(statistics)) that :
$$ x_{norm} = \frac{x - \bar{x}}{\sigma}$$


"Generally, normalization is a process that is used to rescale the real values of a numeric attribute into a range from 0 to 1. Normalization helps organize the data in such a way that it appears similar across all the areas and records. There are various advantages of data normalization, such as redundancy reduction, complexity reduction, clarity, and acquiring higher quality data."

https://www.mygreatlearning.com/blog/numpy-normalization-tutorial/

In [85]:
ran_two_array = np.random.rand(5, 5) *10 # defining a random array of 5 rows and 5 columns using  rand function of random sub module of the numpy library. Here 10 represents the range of the values of the elements which will be between 0 and 10
print(ran_two_array)                       # printing the array
norm = np.linalg.norm(ran_two_array)       # To find the norm of the array
print(norm)                                # Printing the value of the norm
normalized_array = ran_two_array/norm   # Formula used to perform array normalization
print(normalized_array)          

[[0.93244356 0.22687592 6.75602791 5.03067163 1.56118017]
 [6.85768603 4.66574374 0.14340577 3.89609979 6.16425737]
 [8.11165549 0.56006582 3.73929568 2.71703816 3.20650694]
 [8.08160166 0.29681945 0.61153193 1.74786176 5.56714847]
 [4.05503281 9.06461157 1.51917607 2.74448732 1.95907764]]
22.498334565884548
[[0.041445   0.01008412 0.30029013 0.22360196 0.06939092]
 [0.30480861 0.20738174 0.00637406 0.17317281 0.27398727]
 [0.36054471 0.02489366 0.16620322 0.12076619 0.14252197]
 [0.35920888 0.01319295 0.02718121 0.0776885  0.24744714]
 [0.18023702 0.40290145 0.06752393 0.12198624 0.08707656]]


## Stacking numpy arrays

Stacking is used to join a sequence of same dimension arrays along a new axis.

`numpy.stack(arrays,axis)` : It returns a stacked array of the input arrays which has one more dimension than the input arrays.

### You have two ways to do it:


![alt text](./assets/stack.jpeg "stack")


### or


![alt text](./assets/stack2.jpeg "stack")




#### Exercise: Generate two random arrays with integers and apply the stacking using `stack` (★★☆)

In [90]:
a = np.random.randint(0, 100, 10)
b = np.random.randint(0, 100, 10)
print(a,b)
print("Apply stacking")
stacked = np.stack((a,b))
print(stacked)

[74 32 43 91 14 91  0 73 39 28] [25 26 94 70 54 58 17 62 74 97]
Apply stacking
[[74 32 43 91 14 91  0 73 39 28]
 [25 26 94 70 54 58 17 62 74 97]]


#### Exercise: Generate two random arrays with integers and apply the stacking using `hstack` and `vstack` (★★☆)

"The major difference is that np.hstack combines NumPy arrays horizontally and np.vstack combines arrays vertically."

In [92]:
a = np.random.randint(0, 20, 2)
b = np.random.randint(0, 20, 2)

print(np.vstack((a,b)))

print(np.hstack((a,b)))

[[18  7]
 [ 3  5]]
[18  7  3  5]


## Basic maths in numpy

You can make typical math operations like:

- Addition,Subtraction,Multiplication and Division between two arrays using numpy.
- Operation on arrays using sum() & cumsum() function.
- Minimum and Maximum value from an array.
- Exponent/Power , Square Root and Cube Root functions.

or even apply common trigonometric functions:

- `numpy.sin()`:  Sine (x) Function
- `numpy.cos()`: Cosine(x) Function
- `numpy.tan()`: Tangent(x) Function
- `numpy.sinh()`: Hyperbolic Sine (x) Function
- `numpy.cosh()`: Hyperbolic Cosine(x) Function
- `numpy.tanh()`: Hyperbolic Tangent(x) Function
- `numpy.arcsin()`: Inverse Sine(x) Function
- `numpy.arccos()`: Inverse Cosine(x) Function
- `numpy.arctan()`: Inverse Tangent(X) Function
- `numpy.pi`: Pi value π
- `numpy.hypot(w,h)`: For calculating Hypotenuse $c = \sqrt{(w^2 + h^2)}$
- `numpy.rad2deg()`: Radians to degrees
- `numpy.deg2rad()`: Degrees to radians

#### Exercise: Generate two random 8 - dimensional vectors and apply the most common operation between vectors:  addition, substraction, multiplication, division(★☆☆)

>Check the math functions here: https://numpy.org/doc/stable/reference/routines.math.html

In [107]:
r_1 = np.random.randint(1, 10, 8)
r_2 = np.random.randint(1, 10, 8)

print(r_1)
print(r_2)
print("Addition")
print(np.add(r_1,r_2))
print("Substraction")
print(np.subtract(r_1,r_2))
print("Multiplication")
print(np.multiply(r_1,r_2))
print("Division")
print(np.divide(r_1,r_2))



[7 4 9 9 5 4 6 5]
[4 7 7 7 5 8 8 9]
Addition
[11 11 16 16 10 12 14 14]
Substraction
[ 3 -3  2  2  0 -4 -2 -4]
Multiplication
[28 28 63 63 25 32 48 45]
Division
[1.75       0.57142857 1.28571429 1.28571429 1.         0.5
 0.75       0.55555556]


#### Exercise: Generate two random matrices with dimensions between 5 and 10. For example, try 5x7 vs 8x9. Were you able to do the matrix multiplication? why? (★★☆) 

"There are three main ways to perform NumPy matrix multiplication:

**np.dot(array a, array b):** returns the scalar or dot product of two arrays

**np.matmul(array a, array b)**: returns the matrix product of two arrays

**np.multiply(array a, array b):** returns the element-wise matrix multiplication of two arrays"

In [116]:
r1 = np.random.randint(1, 10, (5,7))
r2 = np.random.randint(1, 10, (8,9))

#It’s important to note that we can only multiply two matrices if the number of columns in the first matrix is equal to the number of rows in the second matrix.


# np.dot(r1,r2) # ValueError: shapes (5,7) and (8,9) not aligned: 7 (dim 1) != 8 (dim 0)
# np.matmul(r1,r2) #ValueError: (size 8 is different from 7)

#np.multiply(r1,r2) # ValueError: operands could not be broadcast together with shapes (5,7) (8,9) 

array([[84, 66],
       [95, 81],
       [84, 63],
       [54, 45],
       [44, 38]])

#### Exercise: Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array) Were you able to do the matrix multiplication? (★★☆) 

$$ a = \left(\begin{matrix}
0 & 1 & 2\\ 
3 & 4 & 5\\ 
6 & 7 & 8
\end{matrix}\right)$$

$$ b = \left(\begin{matrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{matrix}\right)$$




In [133]:
a = np.arange(0,9).reshape(3,3)
print(a)

b = np.arange(2,11).reshape(3,3)
print(b)

print(np.dot(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 21  24  27]
 [ 66  78  90]
 [111 132 153]]


#### Exercise: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★★☆)

In [127]:
a = np.random.random((5,3))
print("First matrix:")
print(a)
b = np.random.random((3,2))
print("Second matrix:")
print(b)
c = np.matmul(a, b)
print("Product")
print(c)

First matrix:
[[0.73864756 0.99711069 0.60234462]
 [0.46963915 0.30728332 0.65271959]
 [0.44243073 0.99737885 0.20915235]
 [0.51443626 0.79561162 0.85242699]
 [0.30140099 0.52046845 0.04066741]]
Second matrix:
[[0.64460816 0.69053492]
 [0.70606773 0.10174835]
 [0.16356823 0.27648416]]
Product
[[1.27869036 0.77805505]
 [0.62646025 0.53603443]
 [1.02362216 0.46482284]
 [1.03279547 0.67187093]
 [0.56842341 0.27232861]]


## Data types

Do you think the following preposition is true?

`8==8`

Surely you will definetely say yes, which is true mathematically, but computationally it is not always the same, at least in terms of memory. For example, run the following cell:

In [93]:
import sys

# int64
x = np.array(123)
print("int64: " + str(sys.getsizeof(x)))

# int8
x = np.array(123,dtype=np.int8)
print("int8: " + str(sys.getsizeof(x)))

# float32
x = np.array(123,dtype=np.float32)
print("float32: " + str(sys.getsizeof(x)))

int64: 96
int8: 89
float32: 92


#### It turns out that there are many computational representation of the same number and you can create arrays with different Data Types (dtypes) depending on what you need:

- Boolean : `np.bool_`
- Char : `np.byte`
- Short : `np.short`
- Integer : `np.short`
- Long : `np.int_`
- Float : `np.single`&np.float32`
- Double :`np.double`&`np.float64`
- `np.int8`: integer (-128 to 127)
- `np.int16`:integer( -32768 to 32767)
- `np.int32`: integer(-2147483648 to 2147483647)
- `np.int64`:integer( -9223372036854775808 to 9223372036854775807)


Sometimes, you will need to load, create or export arrays from different data types.


## Harder exercises

The next exercises are related with real situations you could face while you are working in data science and machine learning. Also, we will be frequently talking about matrices and bidimensional arrays.

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

In [ ]:
matrix = np.random.randint(5,size=(3,3))
print(matrix)
promedio = matrix.mean(axis=1, keepdims=True)
print(promedio)
new_matrix = matrix - promedio
print(new_matrix)



[[1 2 3]
 [4 1 2]
 [4 2 1]]
[[2.        ]
 [2.33333333]
 [2.33333333]]
[[-1.          0.          1.        ]
 [ 1.66666667 -1.33333333 -0.33333333]
 [ 1.66666667 -0.33333333 -1.33333333]]


#### Exercise: How to get the dates of yesterday, today and tomorrow? (★★☆)

>Check `np.datetime64`, `np.timedelta64` in numpy (https://numpy.org/doc/stable/reference/arrays.datetime.html)

In [ ]:
today = np.datetime64("today", "D")
print(today)

ayer = today - np.timedelta64(1,"D")
print(ayer)
mañana = today + np.timedelta64(1,"D")
print(mañana)

2022-05-20
2022-05-19
2022-05-21


#### Exercise: How to get all the dates corresponding to the month of December 2022? (★★☆)
Combine `arange`with `datetime`


In [ ]:
np.arange("2022-12","2023-01",dtype="datetime64[D]")

array(['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04',
       '2022-12-05', '2022-12-06', '2022-12-07', '2022-12-08',
       '2022-12-09', '2022-12-10', '2022-12-11', '2022-12-12',
       '2022-12-13', '2022-12-14', '2022-12-15', '2022-12-16',
       '2022-12-17', '2022-12-18', '2022-12-19', '2022-12-20',
       '2022-12-21', '2022-12-22', '2022-12-23', '2022-12-24',
       '2022-12-25', '2022-12-26', '2022-12-27', '2022-12-28',
       '2022-12-29', '2022-12-30', '2022-12-31'], dtype='datetime64[D]')

#### Exercise: Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)

In [ ]:
arreglo = np.random.uniform(1,5,5)
#np.floor(arreglo)
#arreglo.astype(int)
#print(arreglo//1)
#np.trunc(arreglo)

array([2., 1., 2., 4., 1.])

#### Exercise: Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.tile(np.arange(0,5),(5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### Exercise: Consider a generator function that generates 10 integers and use it to build an array (★★☆)

In [ ]:
def generate():
  for x in range(10):
    yield x

Z = np.fromiter(generate(),dtype=int, count= -1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### Exercise: Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### Exercise: Create a random vector of size 10 and sort it (★★☆)

#### Exercise: Consider two random arrays A and B, check if they are equal (★★☆)

#### Exercise: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★★)
>Suggestion: check how to calculate the "square of a matrix"

#### Exercise: Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### Exercise: How to print all the values of an array? (★★☆)

#### Exercise: How to convert a float (32 bits) array into an integer (32 bits) in place?
>Check: https://stackoverflow.com/a/4396247/5989906

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

#### Exercise: How to sort an array by the nth column? (★★☆)

#### Exercise: Find the position of the minimum of a 2D matrix (★★☆)

#### Exercise: Read an image using openCV, check its dimensions, normalize the numbers and show the image (★★★)

>Check: https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

#### Exercise: Considering a four dimensions array, how to get the sum over the last two axis at once? (★★★)

#### Exercise: How to get the diagonal of a dot product? (★★★)

#### Exercise: Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### Exercise: How to swap two rows of an array? (★★★)

#### Exercise: Read an image using openCV and tranpose it. What did you get exactly? Was the image rotated? Moved? Reflected with respect to an axis? (★★★)

#### Exercise: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### Exercise: How to find the most frequent value in an array? (★★★)

#### Exercise: How to get the n largest values of an array (★★★)

#### Exercise: Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### Exercise: Given a two dimensional array, how to extract unique rows? (★★★)

#### Exercise: Can you have an array of strings? Can you mix different data types in the same array? Can you operate (add, sub, mult) arrays with different data types? (★★★)